// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xqzosqviasmubdslgzfm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhxem9zcXZpYXNtdWJkc2xnemZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwODQxMTMsImV4cCI6MjA2MzY2MDExM30.k_-3RID3UoMuDzXcj-1a5SEQtzU5QwLlccKuQvMJRUw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);